# Generated by Django 5.1.2 on 2025-06-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('model_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalModelUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradients', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.device')),
                ('global_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.globalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.device')),
            ],
        ),
        migrations.CreateModel(
            name='DataFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment_id', models.CharField(max_length=10)),
                ('fragment_data', models.BinaryField()),
                ('storage_node', models.CharField(max_length=100)),
                ('is_parity', models.BooleanField(default=False)),
                ('original_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.rawdata')),
            ],
        ),
        migrations.CreateModel(
            name='CachedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_level', models.CharField(choices=[('FREQUENT', 'Frequent Access'), ('LESS_FREQUENT', 'Less Frequent Access'), ('RARE', 'Rarely Accessed')], max_length=20)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('raw_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_management.rawdata')),
            ],
        ),
    ]
