# Generated by Django 5.1.2 on 2025-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edge_processing_time', models.FloatField()),
                ('cloud_processing_time', models.FloatField()),
                ('data_transfer_size', models.FloatField()),
                ('raw_storage_size', models.FloatField()),
                ('encoded_storage_size', models.FloatField()),
            ],
        ),
    ]
